CREATE DATABASE todo_db;

USE todo_db;

CREATE TABLE todoList (
id INT NOT NULL AUTO_INCREMENT,
task_name VARCHAR(45) NOT NULL, 
completed BOOLEAN DEFAULT FALSE,
date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);

SELECT * FROM todoList; 